=== BenMorgan99/framework_j1/src/json_schema/_entitySchema.json
{
    "$schema": "https://json-schema.org/draft-07/schema",
    "$id": "entitySchema",
    "title": "Source System Schema",
    "description": "Defines the structure of the source system contract.",
    "type": "object",
    "required": ["name", "description", "connectionDetails", "ingestion_columns"],
    "additionalProperties": false,
    "properties": {
      "$schema": {
        "description": "JSON Schema URI used for validation",
        "type": "string"
      },
      "name": {
        "description": "The name of the source system.",
        "type": "string"
      },
      "description": {
        "description": "Brief description of source system",
        "type": "string"
      },
      "connectionDetails": {
        "description": "Define how to connect to source system.",
        "type": "object",
        "required": ["connectionString", "sourceQuery"],
        "additionalProperties": false,
        "properties": {
          "connectionString": {
            "type": "string",
            "description": "Connection to data or keyvault secret."
          },
          "sourceQuery": {
            "type": "string",
            "description": "If sql_database - define query to ingest data."
          }
        }
      },
      "ingestion_columns": {
        "description": "List of columns used during ingestion",
        "type": "array",
        "minItems": 1,
        "items": {
          "type": "object",
          "required": ["sortOrder", "columnName", "dataType", "required", "primary_key"],
          "additionalProperties": false,
          "properties": {
            "sortOrder": {
              "type": "integer",
              "minimum": 0
            },
            "columnName": {
              "type": "string",
              "minLength": 1
            },
            "dataType": {
              "type": "string",
              "minLength": 1,
              "enum": [
                "byte", "short", "int", "long",
                "float", "double", "decimal",
                "string", "varchar", "char", "binary",
                "boolean", "date", "timestamp"
              ]
            },
            "required": {
              "type": "boolean"
            },
            "primary_key": {
              "type": "boolean"
            }
          }
        }
      }
    }
  }

=== BenMorgan99/framework_j1/src/contracts/AdventureWorks/customer_AW.json
{
    "name": "customer_AW",
    "description": "dim_customer",
    "connectionDetails": {
        "connectionString": "https://raw.githubusercontent.com/MicrosoftLearning/dp-203-azure-data-engineer/refs/heads/master/Allfiles/labs/03/data/2020.csv",
        "sourceQuery": "None"
    },
    "ingestion_columns": [
        {
            "sortOrder": 1,
            "columnName": "SalesOrderNumber",
            "dataType": "varchar",
            "required": false,
            "primary_key": false
        },
        {
            "sortOrder": 2,
            "columnName": "SalesOrderLineNumber",
            "dataType": "int",
            "required": false,
            "primary_key": false
        },
        {
            "sortOrder": 3,
            "columnName": "OrderDate",
            "dataType": "date",
            "required": false,
            "primary_key": false
        },
        {
            "sortOrder": 4,
            "columnName": "CustomerName",
            "dataType": "varchar",
            "required": true,
            "primary_key": false
        },
        {
            "sortOrder": 5,
            "columnName": "EmailAddress",
            "dataType": "varchar",
            "required": true,
            "primary_key": false
        },
        {
            "sortOrder": 6,
            "columnName": "Item",
            "dataType": "varchar",
            "required": false,
            "primary_key": false
        },
        {
            "sortOrder": 7,
            "columnName": "Quantity",
            "dataType": "int",
            "required": false,
            "primary_key": false
        },
        {
            "sortOrder": 8,
            "columnName": "UnitPrice",
            "dataType": "double",
            "required": false,
            "primary_key": false
        },
        {
            "sortOrder": 9,
            "columnName": "TaxAmount",
            "dataType": "double",
            "required": false,
            "primary_key": false
        }
    ]
}

=== BenMorgan99/framework_j1/solutions/TotesysDB/Contracts/staff.json
{
    "name": "staff",
    "description": "Description of the dim_staff entity",
    "connectionDetails": {
      "connectionString": "connectionStringTotesys",
      "sourceQuery": "SELECT * FROM staff"
    },
    "ingestion_columns": [
      {
        "sortOrder": 1,
        "columnName": "staff_id",
        "dataType": "int",
        "required": true,
        "primary_key": true
      },
      {
        "sortOrder": 2,
        "columnName": "first_name",
        "dataType": "string",
        "required": true,
        "primary_key": false
      },
      {
        "sortOrder": 3,
        "columnName": "last_name",
        "dataType": "string",
        "required": true,
        "primary_key": false
      }
      ,
      {
        "sortOrder": 4,
        "columnName": "department_id",
        "dataType": "int",
        "required": true,
        "primary_key": false
      },
      {
        "sortOrder": 5,
        "columnName": "email_address",
        "dataType": "string",
        "required": true,
        "primary_key": false
      },
      {
        "sortOrder": 6,
        "columnName": "created_at",
        "dataType": "date",
        "required": false,
        "primary_key": false
      },
      {
        "sortOrder": 7,
        "columnName": "last_updated",
        "dataType": "date",
        "required": false,
        "primary_key": false
      }
    ]
  }

=== BenMorgan99/framework_j1/src/contracts/TotesysDB/transaction.json
{
    "$schema": "../../json_schema/_entitySchema.json",
    "name": "transaction",
    "description": "dim_transaction",
    "connectionDetails": {
        "connectionString": "totesysConnectionStringADO",
        "sourceQuery": "SELECT * FROM [transaction]"
    },
    "ingestion_columns": [
        {
            "sortOrder": 1,
            "columnName": "transaction_id",
            "dataType": "int",
            "required": true,
            "primary_key": true
        },
        {
            "sortOrder": 2,
            "columnName": "transaction_type",
            "dataType": "string",
            "required": true,
            "primary_key": false
        },
        {
            "sortOrder": 3,
            "columnName": "sales_order_id",
            "dataType": "int",
            "required": true,
            "primary_key": false
        },
        {
            "sortOrder": 4,
            "columnName": "purchase_order_id",
            "dataType": "int",
            "required": true,
            "primary_key": false
        },
        {
            "sortOrder": 5,
            "columnName": "created_at",
            "dataType": "date",
            "required": false,
            "primary_key": false
        },
        {
            "sortOrder": 6,
            "columnName": "last_updated",
            "dataType": "date",
            "required": false,
            "primary_key": false
        }
    ]
}

=== BenMorgan99/framework_j1/src/contracts/TotesysDB/currency.json
{
    "name": "currency",
    "description": "Description of the dim_currency entity",
    "connectionDetails": {
      "connectionString": "connectionStringTotesys",
      "sourceQuery": "SELECT * FROM currency"
    },
    "ingestion_columns": [
      {
        "sortOrder": 1,
        "columnName": "currency_id",
        "dataType": "int",
        "required": true,
        "primary_key": true
      },
      {
        "sortOrder": 2,
        "columnName": "currency_code",
        "dataType": "string",
        "required": true,
        "primary_key": false
      },
      {
        "sortOrder": 3,
        "columnName": "created_at",
        "dataType": "date",
        "required": false,
        "primary_key": false
      },
      {
        "sortOrder": 4,
        "columnName": "last_updated",
        "dataType": "date",
        "required": false,
        "primary_key": false
      }
    ]
  }

=== BenMorgan99/framework_j1/src/contracts/TotesysDB/design.json
{
    "$schema": "../../json_schema/_entitySchema.json",
    "name": "design",
    "description": "dim_design",
    "connectionDetails": {
        "connectionString": "totesysConnectionStringADO",
        "sourceQuery": "SELECT * FROM design"
    },
    "ingestion_columns": [
        {
            "sortOrder": 1,
            "columnName": "design_id",
            "dataType": "int",
            "required": true,
            "primary_key": true
        },
        {
            "sortOrder": 2,
            "columnName": "created_at",
            "dataType": "date",
            "required": false,
            "primary_key": false
        },
        {
            "sortOrder": 3,
            "columnName": "design_name",
            "dataType": "string",
            "required": true,
            "primary_key": true
        },
        {
            "sortOrder": 4,
            "columnName": "file_location",
            "dataType": "string",
            "required": true,
            "primary_key": false
        },
        {
            "sortOrder": 5,
            "columnName": "file_name",
            "dataType": "string",
            "required": true,
            "primary_key": false
        },
        {
            "sortOrder": 6,
            "columnName": "last_updated",
            "dataType": "date",
            "required": false,
            "primary_key": false
        }
    ]
}

=== BenMorgan99/framework_j1/solutions/TotesysDB/Contracts/department.json
{
    "name": "department",
    "description": "Description of the department entity",
    "connectionDetails": {
      "connectionString": "connectionStringTotesys",
      "sourceQuery": "SELECT * FROM department"
    },
    "ingestion_columns": [
      {
        "sortOrder": 1,
        "columnName": "department_id",
        "dataType": "int",
        "required": true,
        "primary_key": true
      },
      {
        "sortOrder": 2,
        "columnName": "department_name",
        "dataType": "string",
        "required": true,
        "primary_key": false
      },
      {
        "sortOrder": 3,
        "columnName": "location",
        "dataType": "string",
        "required": true,
        "primary_key": false
      },
      {
        "sortOrder": 4,
        "columnName": "manager",
        "dataType": "string",
        "required": true,
        "primary_key": false
      },
      {
        "sortOrder": 5,
        "columnName": "created_At",
        "dataType": "date",
        "required": true,
        "primary_key": false
      },
      {
        "sortOrder": 6,
        "columnName": "last_updated",
        "dataType": "date",
        "required": true,
        "primary_key": false
      }
    ]
  }
